### PR TITLE
build: switch compile to api and update gradle to the latest version

### PR DESCRIPTION
**Pull request by matpag**
Switch deprecated ```compile``` to the new ```api``` keyword and update gradle to the latest stable version

### CODE REVIEW

**Comment by mikepenz** [comment]
@matpag there was a reason to keep it `compile` for the time being. 
The maven release plugin otherwise will ignore those sub dependencies and do not add it into the `pom.xml` which will prevent transitive lib resolving

**Comment by matpag** [comment]
@mikepenz OK sorry, i didn't know the maven plugin script was incompatible with the new api keyword :)
You can close this ^^

**Comment by mikepenz** [comment]
Thanks anyways. 

They claim it should work by now, but just tested and it sadly doesn't: https://github.com/novoda/bintray-release/pull/141

can be checked with 
```
./gradlew generatePomFileForReleasePublication
```

which will generate a `pom-default.xml` and should contain the sub deps

**Comment by matpag** [comment]
I've tried too now, and i can confirm that with `api` keyword is not working correctly.

BTW you could still perform those things:
- Update Gradle to 4.2.1
- Update Novoda Plugin to 0.7.0
- Switch `variant.javaCompile` to `variant.javaCompiler` because `javaCompile` is deprecated in the `gradle-mvn-push.gradle` script: https://plus.google.com/+DanielLew/posts/R124fbhjand

**Comment by mikepenz** [comment]
yes I did update gradle to 4.3 and the novoda plugin to 0.7.0

oh interesting. thanks for the info.

**Pull request closed without merging**
