### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by theapache64**
- Update android icon
- Change hard-coded banner url to relative path

### CODE REVIEW

**Comment by mikepenz** [comment]
I appreciate this PR but sadly I won't be able to merge it as the new android icon does not fit in.

I will have to see and update the raw asset and adjust things to work with the new android branding

**Comment by theapache64** [comment]
Sure, will do an update ASAP.

**Comment by mikepenz** [comment]
I meant I'll have a look at the raw assets and address this ☺️

**Comment by mikepenz** [comment]
merging it because I really appreciate the PR. so you get the `contributor` badge.

**Pull request merged**
