### PR TITLE
Improve NavController support

### PR DESCRIPTION
**Pull request by typebrook**
Allows user to set `NavOptions` and arguments for fragment.

Also, the following orignal NavOptions is always fail to perform "pop up" action
https://github.com/mikepenz/MaterialDrawer/blob/fe1aca9fdea4640b53422a1e9cc9f743e73422c1/library-nav/src/main/java/com/mikepenz/materialdrawer/util/DrawerNavigationUI.kt#L87-L93
 it generates error message:
```
java.lang.IllegalArgumentException: Destination id == 0 can only be used in conjunction with a valid navOptions.popUpTo
```

So let user to set NavOptions (or leave it as null) is necessary.

### CODE REVIEW

**Comment by mikepenz** [comment]
@typebrook thank you so much for your contribution. I will have a look and will get it in as soon as possible :)

**Comment by mikepenz** [comment]
So after looking into it and testing. 

This breaks the "Go to home" navigation.


Try launching the activity. click fragment 1, click "go to home". You will see that it won't navigate to the home fragment

**Comment by typebrook** [comment]
Sorry, my bad. I forgot to manually set NavOptions as null to cowork with `pop up action`.
And that's why I made 259b3d2, pop up action is invalid in current code.

>This breaks the "Go to home" navigation.

Latest commit should solve this. Also, I removed settings for action bar. Let Navigation icon become `back button` looks weird in this case

**Comment by mikepenz** [comment]
Sadly there is still a problem left. 

Click on "Fragment 1", open the drawer, you will see it selected Fragment1
Click on "GO TO HOME", open the drawer, you will see it did not correctly select the item

I think that's because the home item does not match the identifier anymore. 
It should be:
```kotlin
NavigationDrawerItem(R.id.fragmentHome, PrimaryDrawerItem().withName("Home"), null, null),
```
instead. 

Also what would be the expected behavior for `Pop to home`?

**Comment by typebrook** [comment]
>the home item does not match the identifier anymore.

You are right. And it is a bad idea to set action id as field call `destination`. I should fix this and make it more explicit.
https://github.com/mikepenz/MaterialDrawer/blob/259b3d26085740c319e6e51365c70c4970fd8507/library-nav/src/main/java/com/mikepenz/materialdrawer/model/NavigationDrawerItem.kt#L11

>Also what would be the expected behavior for Pop to home?

Clear backstack to home. `GO TO HOME` just adds HomeFragment on stack

**Comment by mikepenz** [comment]
Sounds like a good idea.


Ok. I thought so. But it seems that the clearing the back stack to hike didn't

**Comment by typebrook** [comment]
>But it seems that the clearing the back stack to home didn't work for me either

Now issue should be fixed, see c2a9ac2

**Comment by mikepenz** [comment]
Looks good now. Thank you so much for your work!

**Pull request merged**
