### PR TITLE
Adds fallback listener to manage other drawer items with the NavController

### PR DESCRIPTION
**Pull request by francescogatto**
Added: adds a fallback listener to manage other drawer items with the NavController

### CODE REVIEW

**Comment by mikepenz** [comment]
thank you so much!

**Review by francescogatto — COMMENTED** [review]
You missed a bracket during the branch.. so the build is broken.. 
Thanks!

**Comment by mikepenz** [comment]
@francescogatto thank you so much for the PR. 

I fixed that in some additional cleanup locally in my branch, but couldn't identify to fix it in the PR, the fix is part of the merge though :) 

Didn't want to reopen a new PR to have this count for you as a contribution. 

just for sanity I am having a build re-running now to see if all checks pass

**Comment by francescogatto** [comment]
It's my first time contributing to GitHub.. deleting the branch I lost my contribution? Anyway no problem, the important is that everything works :)

**Comment by mikepenz** [comment]
Great job! Congrats to your first contribution on GitHub

So I can't modify your branch as it's in your fork, but as I wanted to apply some changes I did this locally before merging in. Sadly I did a mistake when doing the merge resolving in the web UI of github. 

Here you can find the changes I did locally before merging: https://github.com/mikepenz/MaterialDrawer/commit/31f3032d08cfa72969c882daa3cae04c38286e01

**Comment by francescogatto** [comment]
Ok! Thanks!
Nice job with this amazing library! 

Ciao! :)

**Pull request merged**
