### PR TITLE
Updated code for newer version of Glide and Picasso

### PR DESCRIPTION
**Pull request by burekas7**
* Picasso: 2.71828
* Glide 4.8.0

Please read all the details here:
https://github.com/mikepenz/MaterialDrawer/issues/2380#issuecomment-431571200

NOTE: Pay attention also to the code addition in the build.gradle.

### CODE REVIEW

**Comment by mikepenz** [comment]
thank you so much. I'll check it asap and try to get it merged ;)

**Comment by mikepenz** [comment]
thank you very much

**Comment by burekas7** [comment]
@mikepenz

You should also update it inside the README.md file.
It still contains the previous Picasso implementation.

**Comment by mikepenz** [comment]
Good point.

**Pull request merged**
