### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by spbisya**
Update build tools version to the latest. Update support lib version to the latest.

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you. 
Isn't there already build tools 25.0.3?

**Comment by spbisya** [comment]
Yes there is. If you want I could perform other pull request with the newest version.

**Comment by mikepenz** [comment]
Just update this one (change it and commit and push to your branch, it will automatically add the new changes to the PR)

**Comment by spbisya** [comment]
Unfortunately, there was not build tools but platform tools. Reverted changes back to 25.0.2.

**Comment by mikepenz** [comment]
oh ok. Sorry mixed them up. Thanks

**Pull request merged**
