### PR TITLE
Make OnDrawerItemSelectedListener and OnDrawerListener classes

### PR DESCRIPTION
**Pull request by RubenGees**

### CODE REVIEW

**Comment by RubenGees** [comment]
The user can select which callback methods he wants to override. -> Removes unnecessary empty methods.

**Comment by mikepenz** [comment]
@RubenGees i know what it does. but i somehow believe that this will just cause troubles for devs who aren't into it. Probably it's an better idea if you create these abstract listener classes inside your application. It's the same as the listener of java are implemented.

**Comment by RubenGees** [comment]
Hmm, okay you have a point there. I saw it in many other libs and loved that feature, because it really avoids a lot of useless code. 

Android Studio shows you a dialog with the overridable methods in it, when you implement the Listener:
dialog
This is from a Library which uses the exact same implementation as in the Pull Request.

**Comment by mikepenz** [comment]
@RubenGees i know how to use it. and how to get this window :D but will others understand this xD. That's the main issue. Keeping it as simple and straight forward as possible :P

**Comment by RubenGees** [comment]
Haha yes, I know what you mean xD

Hmm I don't know. I would really love to see that feature and I think it is always better to make the code "more perfect" even if some users might have to google that for like 3 minutes. 
But of course you have a perfectly valid point here and its your lib after all :)

**Comment by mikepenz** [comment]
@RubenGees i think it's better to add an `AbstractOnDrawerListener` so you will simply use this one then ;)

**Comment by RubenGees** [comment]
Okay! I close this then.

**Pull request closed without merging**
