### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mychaelgo**

### CODE REVIEW

**Comment by mikepenz** [comment]
Not really sure why this is in a merge conflict?

**Comment by mychaelgo** [comment]
Sorry, what conflict did you mean?

**Comment by mikepenz** [comment]
I merged it now. 

Seems like your develp branch you used is very very very very old ;D

**Comment by mychaelgo** [comment]
Oh sorry for that, i forgot to pull the latest commit, anyway thanks for the merge 
😊

**Pull request merged**
