### PR TITLE
Make cleaner dependency management

### PR DESCRIPTION
**Pull request by danielgomezrico**
Make it easy to use dependencies in gradle with just setup.variable or version.variable instead of rootProject.ext.variable.

### CODE REVIEW

**Comment by mikepenz** [comment]
@danielgomezrico oh cool :) looks nice. Thank you

**Comment by mikepenz** [comment]
@danielgomezrico oh we are now in conflict due to the other pull request you created

**Comment by danielgomezrico** [comment]
@mikepenz conflicts fixed.

**Comment by mikepenz** [comment]
@danielgomezrico ok cool. thank you :)

**Pull request merged**
