### PR TITLE
Updated layouts for account header, to center the position of text_switcher.

### PR DESCRIPTION
**Pull request by paolomcgrath**
Centered account_header_drawer_text_switcher in both header layouts and added existing clicklistener in AccountHeader.

### CODE REVIEW

**Comment by paolomcgrath** [comment]
Now centered in compact (and default) as shown here:

unnamed

**Comment by mikepenz** [comment]
@paolomcgrath thanks for the pull request. But as of the Material Design Guidelines for the Navigation Drawer the arrow should not be centered. 

There's already the click listener set for the whole row, so it should be unnecessary to set it again on the arrow.

**Comment by paolomcgrath** [comment]
My apologies, you're correct! The documentation doesn't center the icon, but all of Google's own apps do. The documentation is the best source :)

**Comment by mikepenz** [comment]
@paolomcgrath yeah it's really difficult to find the source of truth in the apps of google :D i just assume we follow the guidelines and in things which are not handled by the guidelines there is the need for different definitions. 

Still thanks for the pull request :). It's great to see people using the MaterialDrawer and try to improve it :)

**Comment by paolomcgrath** [comment]
No problem! I'm using it quite a lot at the moment, so if you're looking for any help with some requests or to improve it, let me know :)

**Comment by mikepenz** [comment]
@paolomcgrath thanks for the offer :). I'm always happy about help or improvements. If you have something you want to add let me know before, there were some requests / pull requests i had to decline because they would not fit within this library. 

Thanks again!

**Pull request closed without merging**
