### PR TITLE
Load profile icon from URL with Picasso.

### PR DESCRIPTION
**Pull request by dsdebastiani**
Added support to load a profile image form an URL with Picasso.

### CODE REVIEW

**Comment by mikepenz** [comment]
@dsdebastiani thanks for the pull request. I would prefer that you create an add-on which can be used in combination with the MaterialDrawer. 

The problem is that most users do not need picasso or the internet permission and if we add this those users will alos have this in their app. 

The MaterialDrawer itself should have no dependencies beside the support libraries. 

Or create a repository containing the modified DrawerItems and i will link to it in a new section within the README.md "plugins/addons".

**Comment by mikepenz** [comment]
@dsdebastiani ok i have to correct one thing. you set the INTERNET permission on the app AndroidManifest missed this. But still including additional dependencies is a really bad idea.

**Comment by Rainer-Lang** [comment]
I don't want additional dependencies.
I wouldn't use the feature.

**Comment by dsdebastiani** [comment]
Ok @mikepenz. You are right. If the app do not needs this feature, won't be nice the MaterialDrawer obligate it to load additional dependencies. In the same way, in some apps, the Iconics library also could be unnecessary, but it is present in the MaterialDrawer dependencies. In this case the Iconics also should be loaded separately, right?

Anyway, in most of cases, the profile picture isn't embedded in the app like as a Drawable, it will be loaded from the internet. My intention was to make it possible using the MaterialDrawer. I just chose Picasso because it's the most common, but could be any other.

So, how would be possible to customize or add this feature, without embed some libraries like Picasso or Glide in the MaterialDrawer dependencies? You said that would be better to create an "plugin/addon", there are some examples how to do that?

I'd be happy to contribute. Thanks for the answer.

**Comment by mikepenz** [comment]
@dsdebastiani loading and setting the profile pictures is already possible with the current implementation. 
You just create the profiles. Create the drawer and it's accountHeader. Then show the ui. in the background the profile images are loaded and as soon as you get them you just update the profile. There's a method for updating a profile identified by its identifier. It's that simple. 

If we are able to find an implementation which wouldn't require the lib included within the MaterialDrawer perhaps with a callback or something so it can be used with any image loading library this would be far better.

**Pull request closed without merging**
