### PR TITLE
Create status_bar_whitespace.md

### PR DESCRIPTION
**Pull request by GreaseMonk**
I was stuck on this for some time, concluded it was the drawer causing it, and didnt immediately notice this function, might come in handy to show this function as well for these cases.

### CODE REVIEW

**Comment by mikepenz** [comment]
@GreaseMonk the sample contains the FullScreenActivity to showcase this ;)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by GreaseMonk** [comment]
Ahh, great :+1:  pardon me in that case

**Comment by mikepenz** [comment]
@GreaseMonk no problem :). if you could add the link to the sample activity and some info regarding it that would be great :) after that i'll merge

**Comment by GreaseMonk** [comment]
better styles, added referral to the sample

**Pull request merged**
