### PR TITLE
added posibility to set rotation angle

### PR DESCRIPTION
**Pull request by kiotoze**
for example when we put param `.withRotationAngle(90)` it will allow arrow rotation from state `>` to `V` and then back from `V` to `>`

### CODE REVIEW

**Comment by mikepenz** [comment]
@kiotoze nice idea. I think if this is possible it should also be possible to set the initial angle too

**Comment by kiotoze** [comment]
@mikepenz you are right. Unfortunately I missed that step. I thought that I have posibility to change arrow icon, but it is hardcoded. So, initial angle make sense.
Should I implement it or you would like to do that?

**Comment by mikepenz** [comment]
@kiotoze please add it to this PR

**Comment by kiotoze** [comment]
I have added changes.
Please check

**Comment by mikepenz** [comment]
@kiotoze looks good. thanks

**Pull request merged**
